### PR TITLE
Add `AllowedIdentifiers` and `AllowedPatterns` configuration option to `RSpec/IndexedLet`

### PR DESCRIPTION
**Pull request by ydah**
Fix: https://github.com/rubocop/rubocop-rspec/issues/1622

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have modified an existing cop's configuration options:

- [x] Set `VersionChanged: "<<next>>"` in `config/default.yml`.

### CODE REVIEW

**Review by pirj — APPROVED** [review]
Thank you!

I suppose if it's needed to share `AllowedIdentifiers` between this ﻿﻿﻿cop and `Naming/VariableNumber`, it can be done with YAML references.

**Comment by bquorning** [comment]
I would rather that we didn’t ask our users to duplicate configuration. But reading configuration from `Naming/VariableNumber` is an anti-pattern, right? (I thought that we read a RuboCop cop’s config from one or two places in this gem, but I cannot find any now.)

**Comment by ydah** [comment]
Oh, there was one thing I overlooked.
[The `AllowedIdentifiers` in `Naming/VariableNumber` must include the suffix.](https://docs.rubocop.org/rubocop/cops_naming.html#allowedidentifiers-capture3) So it may be `AllowedPatterns` that you want as a setting for this cop.

**Review by pirj — APPROVED** [review]
Looks flawless, thank you!

**Comment by ydah** [comment]
Also added `AllowedIdentifiers`.

**Review by bquorning — APPROVED** [review]
Should we mention somewhere that config is read from Naming/VariableNumber also?

**Comment by ydah** [comment]
Indeed it is. I have added documentation👍

**Pull request merged**
