### PR TITLE
Retire RSpec/InvalidPredicateMatcher

### LINKED ISSUE #938: Retire `RSpec/InvalidPredicateMatcher`
> In that case, won’t RSpec tell you about the mistake? Something like

```
expected something to respond to `available??`
```

As far as I remember, according to our non-goals ([a rather incomplete version of what we have in mind](https://docs.rubocop.org/rubocop-rspec/#non-goals-of-rubocop-rspec)) it's not our business to notify the user about things that RSpec will notify with a spec failure, warning, or an error.

I clearly understand that with the editor integration it may highlight this problem earlier.
On the other hand, we don't provide auto-correction anyway.

It's an interesting topic of what we should keep, and what to retire, as this cop might be helpful for some people in some circumstances, but in general, it's not the goal of RuboCop RSpec.

WDYT @bquorning @Darhazer ?

### PR DESCRIPTION
**Pull request by pirj**
Fixes #938

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [-] Added tests.
* [x] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by pirj** [comment]
Ping. For 2.0, after we bump to RuboCop 1.0?

**Comment by bquorning** [comment]
:+1: But we cannot merge yet.

**Comment by bquorning** [comment]
@pirj I’ll rebase this pull request.

**Review by bquorning — APPROVED** [review]
And the build is green.

**Pull request merged**
