### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by Darhazer**
Lets do a release for our friends at FactoryBot

### CODE REVIEW

**Comment by Darhazer** [comment]
Unfortunately - no

**Comment by bquorning** [comment]
It doesn’t look like I have the permissions to give you access… unfortunately. Perhaps @backus can?

**Comment by bquorning** [comment]
I’ll merge this and release.

**Comment by bquorning** [comment]
https://github.com/rubocop-hq/rubocop-rspec/releases/tag/v1.29.1 + https://rubygems.org/gems/rubocop-rspec/versions/1.29.1

**Pull request merged**
