### PR TITLE
Fix new internal affairs cop offences

### PR DESCRIPTION
**Pull request by pirj**
InternalAffairs/NodeMatcherDirective: Preceed def_node_matcher with a @!method YARD directive.

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [-] Added tests.
* [-] Updated documentation.
* [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by pirj** [comment]
JRuby fails with
```
LoadError: no such file to load -- racc/info
```
Do you guys have the superpowers to merge anyway?

**Comment by bquorning** [comment]
> Do you guys have the superpowers to merge anyway?

Yes 😬 

But _why_ does jruby fail?

**Comment by pirj** [comment]
https://github.com/jruby/jruby/issues/6581#issuecomment-786794974 JRuby regression

**Review by bquorning — APPROVED** [review]
Alright, I've remove jruby from the required checks.

**Pull request merged**
