### PR TITLE
Bump version to v1.43.2

### PR DESCRIPTION
**Pull request by bquorning**
As discussed in https://github.com/rubocop-hq/rubocop-rspec/pull/1011#issuecomment-679334188, we have a couple of regression fixes that should be released before the next minor (or major) release goes out.

This branch cherry-picks the merge commits of #1009 and #1011 and changes the version number.

This branch will need to be merged into master afterwards, possibly manually (because of CHANGELOG conflicts), but the tagging and releasing will be done from fd7009b6c1c169f81ec43b9fbff64e6a8398eb03 *before the merge*.

---

Before submitting the PR make sure the following are checked:

* [-] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [-] Added tests.
* [-] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Review by pirj — APPROVED** [review]
🤯 how it's possible to see this as a pull to `master` even though it's on `master` already :D
Thanks!

**Comment by bquorning** [comment]
Oh no, this branch isn’t based on master. It’s just 3 commits on top of https://github.com/rubocop-hq/rubocop-rspec/tree/v1.43.1

**Comment by bquorning** [comment]
https://github.com/rubocop-hq/rubocop-rspec/releases/tag/v1.43.2 is released.

**Comment by pirj** [comment]
This is where my knowledge of git merge commits fails to explain how things are possible.

**Pull request merged**
