### PR TITLE
Stop using newly added cops

### PR DESCRIPTION
**Pull request by pirj**
```
lib/rubocop/cop/rspec/multiple_expectations.rb:73:32: W: Lint/ToEnumArguments: Ensure you correctly provided all the arguments.
              expectations_count = to_enum(:find_expectation, node).count
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
([source](https://app.circleci.com/pipelines/github/rubocop-hq/rubocop-rspec/634/workflows/df5cf9d4-b931-4fd2-af3f-36f4e74276ab/jobs/18146))

We'd still love to use OUR new cops while working on our codebase, let's see how this option works when set under RSpec namespace when we introduce the first pending cop.

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [-] Added tests.
* [-] Updated documentation.
* [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by pirj** [comment]
@bquorning Merge at will.

**Review by bquorning — APPROVED** [review]

**Comment by bquorning** [comment]
> Lint/ToEnumArguments: Ensure you correctly provided all the arguments.

I ran into this again recently. I think it’s actually a bug – see also https://github.com/rubocop/rubocop/pull/8941#issuecomment-1159797356

**Comment by bquorning** [comment]
> We'd still love to use OUR new cops while working on our codebase, let's see how this option works when set under RSpec namespace when we introduce the first pending cop.

It doesn’t work.

```
Warning: RSpec does not support NewCops parameter.

Supported parameters are:

  - Enabled
  - StyleGuideBaseURL
  - Include
  - Language
```

**Comment by pirj** [comment]
What if we define `NewCops: pending` in `config/default.yml` under `RSpec` like [`rubocop` does in its `config/default.yml`](https://github.com/rubocop/rubocop/blob/dfc6e871f2fdc1d0adeeb9139f67ea0ac163857f/config/default.yml#L111)?

This could fix the error, but I'm still uncertain if it would work as intended.

Another concern is if changing the root `NewCops` in project's `.rubocop.yml` would affect `RSpec/NewCops`. It feels that it should, but again I'm uncertain.

**Comment by bquorning** [comment]
> What if we define `NewCops: pending` in `config/default.yml` under `RSpec` like [`rubocop` does in its `config/default.yml`](https://github.com/rubocop/rubocop/blob/dfc6e871f2fdc1d0adeeb9139f67ea0ac163857f/config/default.yml#L111)?

Nope, that doesn’t work :sad_panda:

**Pull request merged**
